# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-06-03 14:39:00
"""
import arcpy, os
from sys import argv
#def #  NOT  IMPLEMENTED# Function Body not implemented

# Disable large xml log files for each shapefile. Requires ArcGIS Pro >10.8
try:
    if arcpy.GetLogMetadata():
        arcpy.SetLogMetadata(False)
    if arcpy.GetLogHistory():
        arcpy.SetLogHistory(False)
except:
        ''

def bdyLength(Scratch, Watersheds, elevPolygs, oid):
    try:
        # To allow overwriting outputs change overwriteOutput option to True.
        arcpy.env.overwriteOutput = True

        Field = "ORIG_FID"

        # Process: Make Feature Layer (Make Feature Layer) (management)
        elevPolyg_Layer = "elevPolyg_"+str(oid)
        arcpy.management.MakeFeatureLayer(in_features=elevPolygs, out_layer=elevPolyg_Layer, where_clause=f"{Field} = {oid}", workspace="", field_info="")

        # Process: Make Feature Layer (Make Feature Layer (2)) (management)
        Watershed_Layer = "watershed_"+str(oid)
        arcpy.management.MakeFeatureLayer(in_features=Watersheds, out_layer=Watershed_Layer, where_clause=f"{Field} = {oid}", workspace="", field_info="")

        # Process: Clip (Clip) (analysis)
        clip = Scratch+"\\clip_"+str(oid)+'.shp'
        arcpy.analysis.Clip(in_features=Watershed_Layer, clip_features=elevPolyg_Layer, out_feature_class=clip, cluster_tolerance="")
        
        # Remove this if using arcpy.SetLogMetadata(False) in ArcGIS Pro version >10.8
        try:
            os.remove(Scratch+"\\clip_"+str(oid)+'.shp.xml')
        except:
            ''

        return oid

    except arcpy.ExecuteError:

        # Geoprocessor threw an error

        return str(oid)+': '+str(arcpy.GetMessages(2))

    except Exception as e:

        # Capture all other errors

        return str(oid)+': '+str(e)
        


if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=argv[1], workspace=argv[1]):
        bdyLength(*argv[1:])
